[colors.primary]
background = '#111318'
foreground = '#e1e2e9'

[colors.selection]
text = '#e1e2e9'
background = '#234776'

[colors.cursor]
text = '#111318'
cursor = '#a6c8ff'

[colors.normal]
black   = '#111318'
red     = '#ff729a'
green   = '#7fff91'
yellow  = '#fff872'
blue    = '#8cb3f2'
magenta = '#2a4776'
cyan    = '#a6c8ff'
white   = '#eff5ff'

[colors.bright]
black   = '#999ea5'
red     = '#ff9fba'
green   = '#a5ffb2'
yellow  = '#fffaa5'
blue    = '#b3d0ff'
magenta = '#c0d8ff'
cyan    = '#d6e6ff'
white   = '#f8fbff'
