[colors.primary]
background = '#0e1514'
foreground = '#dde4e2'

[colors.selection]
text = '#dde4e2'
background = '#00504b'

[colors.cursor]
text = '#0e1514'
cursor = '#81d5cd'

[colors.normal]
black   = '#0e1514'
red     = '#f49d6e'
green   = '#6ad572'
yellow  = '#fff472'
blue    = '#6acac1'
magenta = '#1b625b'
cyan    = '#81d5cd'
white   = '#d2dfde'

[colors.bright]
black   = '#808a89'
red     = '#ffc09f'
green   = '#a5ffac'
yellow  = '#fff8a5'
blue    = '#9beae2'
magenta = '#b8fff8'
cyan    = '#d1fffa'
white   = '#f8fffe'
